name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: apt update
        run: sudo apt update
      - name: Install libxmlsec1
        run: sudo apt-get install -y libxmlsec1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          make install
      - name: Test with pytest
        run: |
          make test
      - name: Run linters
        run: |
          make lint
